FROM mysql:5.7

# link_budget DB:
COPY link_budget.sql /docker-entrypoint-initdb.d/link_budget.sql
#DB users:
RUN echo "CREATE USER 'satellite_lab_pku'@'%' IDENTIFIED BY 'pku_2935';\n\
GRANT ALL PRIVILEGES ON *.* TO 'satellite_lab_pku'@'%';\n\
FLUSH PRIVILEGES;\n" > /docker-entrypoint-initdb.d/user_privileges.sql

ENTRYPOINT ["docker-entrypoint.sh"]
EXPOSE 3306
CMD ["mysqld", "--sql_mode=NO_ENGINE_SUBSTITUTION"]
