version: '2'
services:
#  dagflow_scripts_unit_test:
#    build:
#      context: ./
#      dockerfile: Dockerfile_unit_test
#    image: unit-test
#    hostname: unit-test
#    container_name: unit-test
#    environment:
#      - WAIT_FOR=dagflow_scripts_local_db
#      - WAIT_FOR_PORT=13306
#    volumes:
#      - "./:/dagflow-scripts/script/"
#    depends_on:
#      - dagflow_scripts_local_db

  link_budget_db:
    build:
      context: ./
      dockerfile: dockerfile_db
    image: link_budget_db
    hostname: link_budget_db
    container_name: link_budget_db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=link_budget
    ports:
      - 13306:3306

