version: '2'
services:
  satellite_calculator:
    build:
      context: ../
      dockerfile: dockerfile_restful
    image: hetaobackend7/satellite_calculator
    hostname: satellite_calculator
    container_name: satellite_calculator
    environment:
      - WAIT_FOR=link_budget_db
      - WAIT_FOR_PORT=13306
    volumes:
      - "./log/:/satellite_calculator/log/"
    depends_on:
      - link_budget_db
    ports:
      - 8080:8080

  link_budget_db:
    build:
      context: ./
      dockerfile: dockerfile_db
    image: hetaobackend7/link_budget_db
    hostname: link_budget_db
    container_name: link_budget_db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=link_budget
    volumes:
      - "./mysqldata:/var/lib/mysql"
    ports:
      - 13306:3306

