version: '2.1'
services:
  satellite_calculator:
    build:
      context: ../
      dockerfile: dockerfile_restful
    image: hetaobackend7/satellite_calculator
    hostname: satellite_calculator
    container_name: satellite_calculator
    environment:
      - WAIT_FOR=link_budget_db
      - WAIT_FOR_PORT=3306
    volumes:
      - "./logs/:/satellite_calculator/logs/"
      - "../static/:/satellite_calculator/static/"
    restart: on-failure
    depends_on:
      link_budget_db:
        condition: service_healthy
    links:
      - link_budget_db
    ports:
      - 8080:8080

  link_budget_db:
    build:
      context: ./
      dockerfile: dockerfile_db
    image: hetaobackend7/link_budget_db
    hostname: link_budget_db
    container_name: link_budget_db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=link_budget
    volumes:
      - "./mysqldata:/var/lib/mysql"
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysql", "-u", "root"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 13306:3306

